#!/bin/bash

BUILD_DIR="$2"
basedir="$( cd -P "$( dirname "$0" )" && pwd )"

function sets_framework_yii2() {
    [ $(jq --raw-output '.extra.heroku.framework' < "$BUILD_DIR/composer.json") == "yii2" ]
}

case "$1" in
    detect)
        if [ ! -f "$BUILD_DIR/composer.json" ]; then
            exit 1
        fi

        if sets_framework_yii2; then
            echo "-----> Detected Yii2 app"
            exit 0
        else
            exit 1
        fi
        ;;
    compile)
        echo "-----> Setting up Yii2 app"
        cp "$basedir/../conf/nginx/yii2.conf.erb" "$BUILD_DIR/conf/site.conf.erb"
        ;;
esac
